# Generated by Django 4.2.2 on 2023-09-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email2',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
