# Generated by Django 4.2.2 on 2023-09-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email2',
        ),
    ]
