# Generated by Django 4.2.5 on 2023-09-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopping_cart',
            options={'ordering': ['order_date']},
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
