# Generated by Django 4.2.5 on 2023-09-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_Cart', '0002_alter_shopping_cart_options_shopping_cart_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
    ]
