# Generated by Django 4.2.5 on 2023-09-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_order_products_alter_order_user_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
