# Generated by Django 4.2.5 on 2023-09-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_shopping_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
