# Generated by Django 4.2.2 on 2023-09-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_order_status_orderstatushistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderStatusHistory',
            new_name='Order_Status_History',
        ),
    ]
