# Generated by Django 4.2.5 on 2023-09-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_shopping_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
