# Generated by Django 4.2.2 on 2023-09-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_rename_orderstatushistory_order_status_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_status_history',
            name='status_time',
            field=models.DateTimeField(),
        ),
    ]
