# Generated by Django 4.2.5 on 2023-09-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_of_product',
            field=models.ForeignKey(default='Public', on_delete=django.db.models.deletion.CASCADE, to='Products.product_category'),
        ),
    ]
