# Generated by Django 4.2.2 on 2023-09-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_category',
            old_name='category_id',
            new_name='id',
        ),
    ]
