# Generated by Django 4.2.2 on 2023-09-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_rename_category_id_product_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(blank=True, default='null', on_delete=django.db.models.deletion.CASCADE, to='Products.product_category'),
        ),
    ]
