# Generated by Django 4.2.5 on 2023-09-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_product_category_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_product',
            name='text_review',
            field=models.TextField(blank=True),
        ),
    ]
