# Generated by Django 4.2.5 on 2023-09-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Products', '0005_alter_review_product_text_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_product',
            name='review_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review_product',
            name='review_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='review_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
        migrations.AlterField(
            model_name='review_product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
