# Generated by Django 4.2.5 on 2023-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_remove_product_images_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
