# Generated by Django 4.2.5 on 2023-09-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review_Product',
        ),
    ]
